### ISSUE TITLE
Event creation

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#1]
User Sam Kearley - franchisee - cannot register events. A blank screen appears at page http://fryday.net/admin/event/create-first-step?

**Comment by AndersFryday** [comment]
Fryday Costa Rica not available

http://fryday.net/costa%20rica/costa%20rica/

**Comment by VadimIzmalkov** [comment]
1-st closed with https://github.com/VadimIzmalkov/fryday/commit/94991f441255c19c55212b3a43ecc98aee2f3bb5
2-nd https://github.com/VadimIzmalkov/fryday/commit/adc833aa78be79588068e61d391652074e64bfad
