### ISSUE TITLE
City pages have errors

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#100]
This must be fixed asap. Errors on city pages. 

http://fryday.net/ukraine/kyiv/
<img width="1208" alt="screenshot 2015-10-24 07 50 30" src="https://cloud.githubusercontent.com/assets/10959579/10709212/2ce457b2-7a24-11e5-81b0-e49108bf851a.png">

**Comment by VadimIzmalkov** [comment]
Fixed
