### ISSUE TITLE
Photo report information text unclear

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#101]
Should there be a different text at the photo report to make things more clear? 
http://fryday.net/czech-republic/prague/photo-report/311-fryday-prague-afterwork-at-coco-cafe-disco-bar-2015-10-23
<img width="883" alt="screenshot 2015-10-27 11 06 36" src="https://cloud.githubusercontent.com/assets/10959579/10754914/164c5918-7c9b-11e5-92b6-67c3fe98e901.png">

**Comment by VadimIzmalkov** [comment]
Fixed
