### ISSUE TITLE
User Agreement Update

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#102]
User agreement still not updated with Trade Mark number. 
http://fryday.net/privacy-policy
<img width="1246" alt="screenshot 2015-10-27 13 55 38" src="https://cloud.githubusercontent.com/assets/10959579/10758575/8d016b5e-7cb2-11e5-805c-058d58ca08da.png">

**Comment by VadimIzmalkov** [comment]
Fixed
