### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#11]
When addidng an event the error is occuring. Please see the prnt scrn
![2015-02-18 13 29 10](https://cloud.githubusercontent.com/assets/10962000/6247331/92f028b6-b773-11e4-9067-7d8021451ae8.png)

**Comment by VadimIzmalkov** [comment]
Handeling with last update

**Comment by SamIlona** [comment]
[?]


If you have any questions please do not hesitate to contact me.

Kind regards,

Ilona Samoilenko
Marketing Manager
*Fryday Kyiv*
+41766683683


http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/fryday.kyiv

**Comment by VadimIzmalkov** [comment]
Do you still have this issue??

**Comment by VadimIzmalkov** [comment]
You can reopen that if do

**Comment by SamIlona** [comment]
No, I added the event successfully

If you have any questions please do not hesitate to contact me.

Kind regards,

Ilona Samoilenko
Marketing Manager
*Fryday Kyiv*
+41766683683


http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/fryday.kyiv
