### ISSUE TITLE
Partners to fill in

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#12]
When creating the event I cannot compite it because I need to fill in the info about the partners of the event. But what if I dont have any partners. Whould be good to make it optional.

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/c9dd317abee341ff143e28cea96fe73257191619

**Comment by SamIlona** [comment]
I try to create an event for Budapest without partner and got an error
![2015-02-25 22 10 28](https://cloud.githubusercontent.com/assets/10962000/6380627/504d533a-bd3b-11e4-9408-b28b9e6cf9db.png)

**Comment by VadimIzmalkov** [comment]
Fixed. Please check if everything is ok

**Comment by SamIlona** [comment]
![2015-02-27 15 54 09](https://cloud.githubusercontent.com/assets/10962000/6414598/e1ede404-be98-11e4-8725-a7633b5a8f97.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/614ac032872572c5840cb40385ea3fd9e438d96d
