### ISSUE TITLE
Partners on the city page

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#17]
How to attache partners to the city to see them when you open the city page? 

![2015-02-24 11 58 04](https://cloud.githubusercontent.com/assets/10962000/6347975/6f0fdc36-bc1c-11e4-9757-a12306637469.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/c545614fb003fd927c67b73d570ea6efafbfd8f4
