### ISSUE TITLE
create an event 

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#2]
У Sam проблема с добавлением ивентов: "When I try to create an event of add a venue I just get a blank screen, this is the URL - http://fryday.net/admin/event/create-first-step?
I have tried this on several devices and I get the same response."

**Comment by SamIlona** [comment]
Another user has the same problem - Olesya. "When I press "create event", or "add venue", I receive a blank page and that's it."

**Comment by VadimIzmalkov** [comment]
Closed with commit https://github.com/VadimIzmalkov/fryday/commit/94991f441255c19c55212b3a43ecc98aee2f3bb5

**Comment by VadimIzmalkov** [comment]
Closed with commit https://github.com/VadimIzmalkov/fryday/commit/94991f441255c19c55212b3a43ecc98aee2f3bb5

**Comment by SamIlona** [comment]
Thank you! I will try now.

If you have any questions please do not hesitate to contact me.

Kind regards,

Ilona Samoilenko
Marketing Manager
*Fryday Kyiv*
+41766683683


http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/fryday.kyiv
