### ISSUE TITLE
newsletters

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#20]
When you actually sending the newsletter you dont know if it was sent because you have the sign  'Importing started in background'  but you dont know if it was successfully or not at the end. Hans today sent one to his database. Neither him or me didnt receive it. How can we know if ir was sent? confirmation? statistic?

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/599a03d50e7a11355f851007f188d5bdabe10893
