### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#21]
the error occured when i try to subscribe. 
![2015-02-25 12 11 19](https://cloud.githubusercontent.com/assets/10962000/6369531/9e56e130-bce7-11e4-916c-dc350d4a3aa0.png)

**Comment by VadimIzmalkov** [comment]
Am I right understand you - when you try to add subscriber?

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/c9dd317abee341ff143e28cea96fe73257191619

**Comment by SamIlona** [comment]
yes. correct.
