### ISSUE TITLE
User Costa Rica fail to add event

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#26]
An error occurred
An error occurred during execution; please try again later.
Additional information:
Doctrine\ORM\NonUniqueResultException

File:
/var/www/html/fryday/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:657
Message:
Stack trace:
#0 /var/www/html/fryday/module/Admin/src/Admin/Entity/Repository/EventRepository.php(101): Doctrine\ORM\AbstractQuery->getSingleResult()
#1 /var/www/html/fryday/module/Admin/src/Admin/Controller/EventController.php(275): Admin\Entity\Repository\EventRepository->getEventBySlug('fryday-afterwor...', '06032015')
#2 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Admin\Controller\EventController->preViewAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/fryday/public/index.php(26): Zend\Mvc\Application->run()
#13 {main}

**Comment by VadimIzmalkov** [comment]
Cannot reproduce. Please advise

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/614ac032872572c5840cb40385ea3fd9e438d96d
