### ISSUE TITLE
Add partner

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#28]
I cannot add a new partner logo. Neither when correcting it.

![2015-02-27 10 20 15](https://cloud.githubusercontent.com/assets/10962000/6409945/46c72874-be6a-11e4-87f8-c6858bdff798.png)

**Comment by SamIlona** [comment]
![2015-02-27 10 24 08](https://cloud.githubusercontent.com/assets/10962000/6410002/ca580ac8-be6a-11e4-808e-cb68dc88224d.png)

**Comment by VadimIzmalkov** [comment]
The issue that tiff format not supported. Use jpeg, jpg, png

**Comment by SamIlona** [comment]
Thank you!

**Comment by VadimIzmalkov** [comment]
I will add notification about it.

**Comment by VadimIzmalkov** [comment]
validator added
