### ISSUE TITLE
Create a new event

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#29]
I dont see the "Newsletter About Event" to fill in. 

![2015-02-27 10 30 42](https://cloud.githubusercontent.com/assets/10962000/6410198/4fdf279c-be6d-11e4-8081-e8d54182d15e.png)
 
After saving the event, appears the logo of the partner instead of the logo of the venue. 

![2015-02-27 10 45 52](https://cloud.githubusercontent.com/assets/10962000/6410250/f95e8d12-be6d-11e4-84f2-2ad7a3ef860a.png)

**Comment by SamIlona** [comment]
Cannot publish the same event ((

![2015-02-27 13 01 43](https://cloud.githubusercontent.com/assets/10962000/6412188/ed977e7c-be80-11e4-83a2-04d8ec42311b.png)

**Comment by VadimIzmalkov** [comment]
publishing fixed.. rest is in progress

**Comment by SamIlona** [comment]
Please fix the venue logo on the newsletter preview ASAP. It shows logo of the partner instead of the venue. Thanks.

**Comment by SamIlona** [comment]
I got a new problem. The logo of the venue doesnt sgow off at all and info about the event too. 

![2015-03-02 14 34 28](https://cloud.githubusercontent.com/assets/10962000/6441723/e82c87e0-c0ea-11e4-90bd-019597f67bc2.png)

**Comment by SamIlona** [comment]
Everything is normal for the next event I just created. Thus i am not sure where is the problem but it isn't always appearing. 

![2015-03-02 15 04 45](https://cloud.githubusercontent.com/assets/10962000/6442119/ad4f465a-c0ed-11e4-9d71-d0307abe62c2.png)

**Comment by SamIlona** [comment]
Another event got problem with the logo: 

![2015-03-02 16 29 27](https://cloud.githubusercontent.com/assets/10962000/6443750/5e091c90-c0f9-11e4-8326-2c176c2185f5.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/7b6928777aac16490dd9fcc875a458e4686614ca
