### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#31]
Error occurred when I added the profile of Sam

![2015-02-27 14 34 02](https://cloud.githubusercontent.com/assets/10962000/6413269/fffcbfd4-be8d-11e4-93e6-b97dd6ed32a7.png)

**Comment by SamIlona** [comment]
The same for other user:

![2015-02-27 14 53 40](https://cloud.githubusercontent.com/assets/10962000/6413505/77de090c-be90-11e4-8333-9a44ae83da8b.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/68c6d70ed8bd5e8a087cc5ba306ce4039936fcce

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/68c6d70ed8bd5e8a087cc5ba306ce4039936fcce

**Comment by SamIlona** [comment]
perfect!

If you have any questions please do not hesitate to contact me.

Kind regards,

Ilona Samoilenko
Marketing Manager
*Fryday Kyiv*
+41766683683


http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/fryday.kyiv
