### ISSUE TITLE
Event from Kharkov

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#32]
An error occurred when saved the event

![2015-02-27 15 08 37](https://cloud.githubusercontent.com/assets/10962000/6413699/84e7553e-be92-11e4-92a8-1a5e8fee685c.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/614ac032872572c5840cb40385ea3fd9e438d96d
