### ISSUE TITLE
partners

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#33]
One problem popped up. When I am editing the event this new function is appearing and I cannot save the event because it must be filled in.  This is afterwork event and has no partners.

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/c2e7fa7e77b816a2a293518361f77fff0ff608f6

**Comment by SamIlona** [comment]
Perfect! Thanks a lot!

If you have any questions please do not hesitate to contact me.

Kind regards,

Ilona Samoilenko
Marketing Manager
*Fryday Kyiv*
+41766683683


http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/fryday.kyiv
