### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#34]
I cannot create profiles for Riga and Budapest because the e-mail is used. The e-mails were used in the profiles which were not successful. How can I create now a new profiles or add the old ones?

As well cannot access to the Odessa profile because the password is not suiting. Can we reset it?

**Comment by VadimIzmalkov** [comment]
temp fix https://github.com/VadimIzmalkov/fryday/commit/cc2c7ba02217b3c4330773567bc157c3661ea2f6
