### ISSUE TITLE
View past events

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#35]
I try to view last nights event in Kyiv but end up at a blank page. The events should be archived and available for viewing for many reasons. 

http://fryday.net/ukraine/kyiv/event/04032015/fryday-w-with-mr-luc-chenier
![screenshot 2015-03-05 07 50 26](https://cloud.githubusercontent.com/assets/10959579/6500464/5177a554-c30c-11e4-9e05-4a645c7a79ba.png)

**Comment by VadimIzmalkov** [comment]
the event at http://fryday.net/ukraine/kyiv/event/35/fryday-w-with-mr-luc-chenier

To have an unique url for each event I chanchged the routes
