### ISSUE TITLE
Partners page

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#4]
Когда захожу на pertners page появляется белый лист с неполным перечнем партнеров.
![2015-02-11 19 06 59](https://cloud.githubusercontent.com/assets/10962000/6152942/2e7591de-b221-11e4-8a4e-40341812d1d6.png)

**Comment by SamIlona** [comment]
The same with the Venue page

![2015-02-12 11 38 35](https://cloud.githubusercontent.com/assets/10962000/6165888/b5ea1c4a-b2ab-11e4-839d-24f4438496fa.png)

**Comment by VadimIzmalkov** [comment]
Closed
