### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#44]
I have problem with the Janis profile. It is 3rd time I an creating it and having an issue. Please help me that I could connect him to the site. 

![2015-03-12 12 38 48](https://cloud.githubusercontent.com/assets/10962000/6617065/e574f8ee-c8b4-11e4-950e-114b4d6875f0.png)

**Comment by SamIlona** [comment]
And profile of Veronika as well when saaving. 

![2015-03-12 12 50 22](https://cloud.githubusercontent.com/assets/10962000/6617186/6f5a35be-c8b6-11e4-8c21-7b7aa235dea1.png)

**Comment by VadimIzmalkov** [comment]
issue not present any more
