### ISSUE TITLE
Mailer appears not to work

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#46]
http://fryday.net/admin/mailer/index

![screenshot 2015-03-13 12 18 39](https://cloud.githubusercontent.com/assets/10959579/6636693/2cd739b0-c97b-11e4-8ecb-8ead90dd0afb.png)

**Comment by VadimIzmalkov** [comment]
Fixed

**Comment by VadimIzmalkov** [comment]
Fixed
