### ISSUE TITLE
URL for city partners

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#49]
Partners listed on city pages should have links to partner home page etc. Not just listed in the admin section but real links on the public site. 
![screenshot 2015-03-16 21 13 03](https://cloud.githubusercontent.com/assets/10959579/6674305/6857e874-cc21-11e4-906e-d3787e6eb02b.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/a4f335e188aeb86367b4310f76e95887a5279945
