### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#65]
I have a problem with 2 profiles. I am not sure would it be better to correct or delete? I will need to use the budapest e-mail for another franchisor. 

![2015-04-07 12 39 54](https://cloud.githubusercontent.com/assets/10962000/7022024/cf0a109e-dd27-11e4-83b2-018c569ae817.png)
![2015-04-07 12 43 05](https://cloud.githubusercontent.com/assets/10962000/7022026/d5f8ef2e-dd27-11e4-84fc-4c2909bafc48.png)

**Comment by VadimIzmalkov** [comment]
issue not present anymore
