### ISSUE TITLE
add user

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#66]
I cannot add a new user as the e-mail is not accepted: caotlam@gmail.com & fryday.dnipropetrovsk@gmail.com 

![image](https://cloud.githubusercontent.com/assets/10962000/7136458/68f29b66-e2b1-11e4-8da9-f8e105841c8c.png)

**Comment by SamIlona** [comment]
As well  this e-mail (fryday.bucharest@gmail.com) is in use. Could we make it free? I would like to add the franchisor on this e-mail.

**Comment by SamIlona** [comment]
The same for this e-mail fryday.budapest@gmail.com

**Comment by VadimIzmalkov** [comment]
Not actual
