### ISSUE TITLE
Add subscribers

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#72]
Adding subscribers should be made possible just by dumping email addresses in a field like on LinkedIn. Many franchisees are not very experienced computer and Internet users and we can expect the number of problems adding subscribers to continue if an easier solution is not implemented. 

https://www.linkedin.com/fetch/importAndInviteEntry?trk=nav_responsive_sub_nav_add_connections
![screenshot 2015-05-06 11 27 12](https://cloud.githubusercontent.com/assets/10959579/7490708/19be88f0-f3e3-11e4-86d5-302cee4338e6.png)

**Comment by VadimIzmalkov** [comment]
Implemented
