### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#79]
Can we log users (franchisees) to see who signed in when from where and what pages they visited, documents they downloaded etc?

**Comment by VadimIzmalkov** [comment]
Yes, I already thought about that. Put this task in queue

**Comment by AndersFryday** [comment]
Super. 

Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On May 18, 2015, at 12:33 PM, Vadim Izmalkov <notifications@github.com> wrote:

Yes, I already thought about that. Put this task in queue

**Comment by VadimIzmalkov** [comment]
Added.
