### ISSUE TITLE
Problem listing event for Fryday Warsaw - urgent

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#81]
#0 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('getEntityManage...', true)
#1 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/PluginManager.php(84): Zend\ServiceManager\AbstractPluginManager->get('getEntityManage...', NULL, true)
#2 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(292): Zend\Mvc\Controller\PluginManager->get('getEntityManage...', NULL)
#3 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(307): Zend\Mvc\Controller\AbstractController->plugin('getEntityManage...')
#4 /var/www/html/fryday/module/Admin/src/Admin/Controller/EventController.php(429): Zend\Mvc\Controller\AbstractController->__call('getEntityManage...', Array)
#5 /var/www/html/fryday/module/Admin/src/Admin/Controller/EventController.php(429): Admin\Controller\EventController->getEntityManager()
#6 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Admin\Controller\EventController->preViewAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/fryday/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/html/fryday/public/index.php(26): Zend\Mvc\Application->run()
#17 {main}
![screenshot 2015-06-05 11 11 02](https://cloud.githubusercontent.com/assets/10959579/8003276/5f5de1ee-0b76-11e5-868d-960b5fa672cc.png)

**Comment by VadimIzmalkov** [comment]
fixed
