### ISSUE TITLE
Unsubscribe link not working in emails? Confirmation of unsubscribe needed?

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#84]
I would like to unsubscribe from your emails, however, the link at the bottom of your email does not seem to work
Therefore kindly remove my email address from your mailing list.
 
Thank you
 
Lenka Oleksiakova
Senior Associate | Czech Republic
Industrial Agency 
Main  +420 226 537 618
lenka.oleksiakova@colliers.com

Colliers International
Slovansky dum, Na Prikope  859/22 | Prague 1, 11000 | Czech Republic
www.colliers.cz

**Comment by VadimIzmalkov** [comment]
Yes, after last update it stop to work. Will be fixed with next update

**Comment by AndersFryday** [comment]
Okay. Good. 

Does it normally give the member a confirmation?

Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On Jun 18, 2015, at 10:07 AM, Vadim Izmalkov <notifications@github.com> wrote:

Yes, after last update it stop to work. Will be fixed with next update

**Comment by VadimIzmalkov** [comment]
Fixed
