### ISSUE TITLE
Password reset error

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#86]
The link takes you to the page to submit the email address, not to write a new password. 
![screen shot 2015-06-26 at 11 05 04 am](https://cloud.githubusercontent.com/assets/10959579/8374175/8031aa44-1bf3-11e5-8c24-97b3f43826d2.png)
![screen shot 2015-06-26 at 11 04 48 am](https://cloud.githubusercontent.com/assets/10959579/8374176/8034bdec-1bf3-11e5-9940-a1690d7a26b0.png)

**Comment by VadimIzmalkov** [comment]
Yes I know it. When I created your account it wasn't connected to
registration id. Now I added this parameter. To make it working new account
should be created. When I finish all updates it will work

**Comment by AndersFryday** [comment]
Aha. Very good. 

Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On Jun 26, 2015, at 11:15 AM, Vadim Izmalkov <notifications@github.com> wrote:

Yes I know it. When I created your account it wasn't connected to
registration id. Now I added this parameter. To make it working new account
should be created. When I finish all updates it will work

**Comment by VadimIzmalkov** [comment]
Fixed
