### ISSUE TITLE
Facebook sign in error

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#88]
http://fryday.net/accounts/facebook/auth/?error_code=4201&error_message=User+canceled+the+Dialog+flow&state=315c75c40f7b97de9f6475b018a9ef0d#_=_

![screenshot 2015-06-29 08 07 06](https://cloud.githubusercontent.com/assets/10959579/8401903/e5cfffd8-1e35-11e5-8fb5-fc7bb6f86b5f.png)

**Comment by VadimIzmalkov** [comment]
Hi Anders!

When does this error occurs, and what are conditions?

Best regards,
Vadim

**Comment by AndersFryday** [comment]
When I tried to sign in using my FB account. That FB account has anders@ostlund.se as email, the same email I use for Fryday.net. 

Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On Jun 29, 2015, at 8:32 AM, Vadim Izmalkov <notifications@github.com> wrote:

Hi Anders!

When does this error occurs, and what are conditions?

Best regards,
Vadim

**Comment by VadimIzmalkov** [comment]
Have you tried to sign in into fryday.net via facebook before?

**Comment by VadimIzmalkov** [comment]
The problem might be in cookie. Can you please clear the cookie and try
again. If that true, I will fix it

**Comment by VadimIzmalkov** [comment]
I see the scope - user_events. This scope was before, I have deleted that

**Comment by AndersFryday** [comment]
Does this means it is fixed now? 

Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On Jun 29, 2015, at 8:59 AM, Vadim Izmalkov <notifications@github.com> wrote:

I see the scope - user_events. This scope was before, I have deleted that

**Comment by VadimIzmalkov** [comment]
No, because I can not see this problem on my side. If you delete cookie and
problem will disappear - I know exactly why login failed.

**Comment by AndersFryday** [comment]
Hi Vadim!

I tried again and came longer this time but it tells me I have no access because I am not app admin. 
https://www.facebook.com/v2.3/dialog/oauth?redirect_uri=http%3A%2F%2Ffryday.net%2Faccounts%2Ffacebook%2Fauth%2F&state=684f3ac37963dab016190f8fb90e9cde&scope=email&client_id=500706906754868&ret=login


Best Regards,
Anders

********************************************
Fryday – the movie!

English:
http://youtu.be/hy6nxFMO104

Russian: 
http://youtu.be/mWUKPiYkv08 

Fryday Afterwork in Kyiv:
http://youtu.be/Nyw9np-z53w

Fryday W:
http://youtu.be/YT7UYJJdUQY 

www.fryday.net 

anders@ostlund.se
http://ua.linkedin.com/in/andersostlund
http://twitter.com/andersostlund
http://www.facebook.com/ostlundanders 
http://www.facebook.com/fryday.kyiv





On Jun 29, 2015, at 11:18 AM, Vadim Izmalkov <notifications@github.com> wrote:

No, because I can not see this problem on my side. If you delete cookie and
problem will disappear - I know exactly why login failed.

**Comment by VadimIzmalkov** [comment]
Email/Facebook account the same (anders@ostlund.se) ?
<anders@ostlund.se>

**Comment by VadimIzmalkov** [comment]
Fixed
