### ISSUE TITLE
User to remove

### ISSUE THREAD

**Issue by SamIlona** [VadimIzmalkov/fryday#9]
Was attached to the city by mistake Merey in Almaty. 

![2015-02-12 11 54 03](https://cloud.githubusercontent.com/assets/10962000/6166168/0b1f36c6-b2ae-11e4-8285-0ccc3b7154ea.png)

**Comment by VadimIzmalkov** [comment]
https://github.com/VadimIzmalkov/fryday/commit/7296702e710922d8aad5c8e19755ec5a267041bf
