### ISSUE TITLE
Error http://fryday.net/account/

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#91]
/var/www/html/fryday/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php:317

Route with name "copy" not found

#0 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Router/Http/Part.php(210): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#1 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(330): Zend\Mvc\Router\Http\Part->assemble(Array, Array)
#2 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Router/Http/Part.php(210): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(351): Zend\Mvc\Router\Http\Part->assemble(Array, Array)
#4 /var/www/html/fryday/vendor/zendframework/zend-view/src/Helper/Url.php(100): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#5 [internal function]: Zend\View\Helper\Url->__invoke('account/contact...')
#6 /var/www/html/fryday/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(393): call_user_func_array(Object(Zend\View\Helper\Url), Array)
#7 /var/www/html/fryday/module/Fryday/view/fryday/account/dashboard-administrator.phtml(10): Zend\View\Renderer\PhpRenderer->__call('url', Array)
#8 /var/www/html/fryday/module/Fryday/view/fryday/account/dashboard-administrator.phtml(10): Zend\View\Renderer\PhpRenderer->url('account/contact...')
#9 /var/www/html/fryday/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/var/www/html/f...')
#10 /var/www/html/fryday/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#11 /var/www/html/fryday/vendor/zendframework/zend-view/src/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 /var/www/html/fryday/vendor/zendframework/zend-view/src/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#13 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/fryday/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/fryday/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#17 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/fryday/vendor/zendframework/zend-mvc/src/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#19 /var/www/html/fryday/public/index.php(26): Zend\Mvc\Application->run()
#20 {main}
<img width="1236" alt="screenshot 2015-08-19 08 45 58" src="https://cloud.githubusercontent.com/assets/10959579/9350244/23aa15fa-464f-11e5-9563-a8b684cd0568.png">

**Comment by VadimIzmalkov** [comment]
Fixed
