### ISSUE TITLE
Fryday Kyiv not loading

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#93]
http://fryday.net/ukraine/kyiv/
<img width="1275" alt="screen shot 2015-09-15 at 11 47 02 am" src="https://cloud.githubusercontent.com/assets/10959579/9873350/8ca62bec-5b9f-11e5-98b2-9b0f19c76089.png">

**Comment by VadimIzmalkov** [comment]
Fixed
