### ISSUE TITLE
Urgent! City pages have error

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#98]
The city page error have to be fixed asap. Representatives hate it when their city page is not correct. 

http://fryday.net/pakistan/islamabad/

<img width="1180" alt="screenshot 2015-10-21 19 11 38" src="https://cloud.githubusercontent.com/assets/10959579/10644203/a4d5c58e-7827-11e5-95b8-c49f6cb88bb3.png">

**Comment by VadimIzmalkov** [comment]
Fixed
