### ISSUE TITLE
Change signed-up to signed-in

### ISSUE THREAD

**Issue by AndersFryday** [VadimIzmalkov/fryday#99]
When new users join Fryday it is called "Signed-up". When an existing user is coming back it should be called "signed-in". 

http://fryday.net/account/users/team
<img width="859" alt="screenshot 2015-10-22 14 58 23" src="https://cloud.githubusercontent.com/assets/10959579/10665704/66ad550a-78cd-11e5-96f6-ed3f1902f108.png">

**Comment by VadimIzmalkov** [comment]
Fixed
